namespace AlarmProgram.Domain;

public enum MachineEventType
{
    Unknown = 0,
    Startup = 1,
    Shutdown = 2,
    Restart = 3,
    UnexpectedShutdown = 4,
    UserLogon = 5,
    Heartbeat = 6,
    IpChanged = 7,
    NetworkOffline = 8,
    NetworkOnline = 9,
    SystemResume = 10,
    UserLogoff = 11,
    SessionLock = 12,
    SessionUnlock = 13,
    LowDiskSpace = 14,
    BatteryLow = 15,
    AcPowerLost = 16,
    AcPowerRestored = 17,
    ProcessDown = 18,
    HighCpu = 19,
    HighMemory = 20,
    RdpConnected = 21,
    RdpDisconnected = 22,
    ServiceDown = 23,
    UsbConnected = 24,
    UsbDisconnected = 25,
    DailyDigest = 26,
    FailedLogon = 27,
    ApplicationCrash = 28,
    RebootPending = 29,
    ApplicationHang = 30,
    DefenderThreat = 31,
    WindowsUpdateFailed = 32,
    DiskError = 33,
    StatusSnapshot = 34
}
